# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogEditorTurnosPorEmpleado.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(609, 423)
        Dialog.setMinimumSize(QtCore.QSize(609, 423))
        Dialog.setMaximumSize(QtCore.QSize(609, 423))
        Dialog.setAcceptDrops(False)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.line = QtGui.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 30, 581, 16))
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 120, 261, 261))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.tableWidget = QtGui.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 241, 231))
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(60)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(280, 120, 311, 261))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 200, 20, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.addButton = QtGui.QPushButton(self.groupBox_2)
        self.addButton.setGeometry(QtCore.QRect(220, 230, 81, 23))
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.calendarioDia = QtGui.QCalendarWidget(self.groupBox_2)
        self.calendarioDia.setGeometry(QtCore.QRect(36, 20, 261, 133))
        self.calendarioDia.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Spain))
        self.calendarioDia.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarioDia.setGridVisible(False)
        self.calendarioDia.setHorizontalHeaderFormat(QtGui.QCalendarWidget.SingleLetterDayNames)
        self.calendarioDia.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.calendarioDia.setNavigationBarVisible(False)
        self.calendarioDia.setObjectName(_fromUtf8("calendarioDia"))
        self.eliminarButton = QtGui.QPushButton(self.groupBox_2)
        self.eliminarButton.setGeometry(QtCore.QRect(140, 230, 75, 23))
        self.eliminarButton.setObjectName(_fromUtf8("eliminarButton"))
        self.siguienteButton = QtGui.QPushButton(self.groupBox_2)
        self.siguienteButton.setGeometry(QtCore.QRect(210, 160, 91, 23))
        self.siguienteButton.setObjectName(_fromUtf8("siguienteButton"))
        self.comboTurno = QtGui.QComboBox(self.groupBox_2)
        self.comboTurno.setGeometry(QtCore.QRect(36, 200, 263, 20))
        self.comboTurno.setEditable(False)
        self.comboTurno.setObjectName(_fromUtf8("comboTurno"))
        self.comboTurno.addItem(_fromUtf8(""))
        self.comboTurno.addItem(_fromUtf8(""))
        self.anteriorButton = QtGui.QPushButton(self.groupBox_2)
        self.anteriorButton.setGeometry(QtCore.QRect(34, 160, 91, 23))
        self.anteriorButton.setObjectName(_fromUtf8("anteriorButton"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 15, 22))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.hoyButton = QtGui.QPushButton(self.groupBox_2)
        self.hoyButton.setGeometry(QtCore.QRect(130, 160, 75, 23))
        self.hoyButton.setObjectName(_fromUtf8("hoyButton"))
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(290, 70, 291, 31))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.mesLabel = QtGui.QLabel(self.frame)
        self.mesLabel.setGeometry(QtCore.QRect(0, 0, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.mesLabel.setFont(font)
        self.mesLabel.setText(_fromUtf8(""))
        self.mesLabel.setObjectName(_fromUtf8("mesLabel"))
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 50, 261, 61))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.labelApellidos = QtGui.QLabel(self.groupBox_3)
        self.labelApellidos.setGeometry(QtCore.QRect(67, 37, 182, 12))
        self.labelApellidos.setText(_fromUtf8(""))
        self.labelApellidos.setObjectName(_fromUtf8("labelApellidos"))
        self.labelNombre = QtGui.QLabel(self.groupBox_3)
        self.labelNombre.setGeometry(QtCore.QRect(67, 20, 182, 11))
        self.labelNombre.setText(_fromUtf8(""))
        self.labelNombre.setObjectName(_fromUtf8("labelNombre"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 37, 51, 12))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(10, 20, 44, 11))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.botonAplicar = QtGui.QPushButton(Dialog)
        self.botonAplicar.setGeometry(QtCore.QRect(500, 390, 81, 23))
        self.botonAplicar.setObjectName(_fromUtf8("botonAplicar"))
        self.botonOk = QtGui.QPushButton(Dialog)
        self.botonOk.setGeometry(QtCore.QRect(412, 390, 82, 23))
        self.botonOk.setObjectName(_fromUtf8("botonOk"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Editor de trabajador/a", None))
        self.label_5.setText(_translate("Dialog", "Guardias", None))
        self.groupBox.setTitle(_translate("Dialog", "Guardias del mes", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Día", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Turno", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Especial", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Añadir guardias", None))
        self.label_6.setText(_translate("Dialog", "Tipo", None))
        self.addButton.setText(_translate("Dialog", "Añadir", None))
        self.eliminarButton.setText(_translate("Dialog", "Eliminar", None))
        self.siguienteButton.setText(_translate("Dialog", "Siguiente", None))
        self.comboTurno.setItemText(0, _translate("Dialog", "A", None))
        self.comboTurno.setItemText(1, _translate("Dialog", "B", None))
        self.anteriorButton.setText(_translate("Dialog", "Anterior", None))
        self.label_4.setText(_translate("Dialog", "Día", None))
        self.hoyButton.setText(_translate("Dialog", "Hoy", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Trabajador/a", None))
        self.label_2.setText(_translate("Dialog", "Apellidos", None))
        self.label.setText(_translate("Dialog", "Nombre", None))
        self.botonAplicar.setText(_translate("Dialog", "Aplicar", None))
        self.botonOk.setText(_translate("Dialog", "Aceptar", None))

